name: Frontend Release

on:
  push:
    tags:
      - 'v*' # 例如 v1.0.0

permissions:
  contents: write  # 上传 Release 权限

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm run build
          cd dist
          zip -r ../dist.zip *

      - name: Upload Release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip
